#!/usr/bin/env bash
#
#   Lists contents of a directory including an ascii 
#   descriptor file (e.g. README)
#
#   Marcus Koehler, ECMWF
#


#-- define an array of possible descriptor file names
readme_files=("00_README" "README.md" ".readme" "README" "README.txt" ".README")


#-- switch output colour to one of the following (the two digits before "m"):
black='\e[0;30m'
dark_gray='\e[1;30m'

red='\e[1;31m'
green='\e[1;32m'
yellow='\e[1;33m'
blue='\e[1;34m'
magenta='\e[1;35m'
cyan='\e[1;36m'
white='\e[1;37m'

dim_red='\e[0;31m'
dim_green='\e[0;32m'
dim_yellow='\e[0;33m'
dim_blue='\e[0;34m'
dim_magenta='\e[0;35m'
dim_cyan='\e[0;36m'
dim_white='\e[0;37m'

NC='\e[0m'   # set default colour

#-- select the colour for the descriptor file contents
echo -e ${cyan}

#-- check if any of the files exist
found=false
for file in "${readme_files[@]}"; do
    if [ -e "$file" ]; then
        found=true
        break  # Stop checking after finding the first existing file
    fi
done

#-- if no descriptor files exist, print a message and exit
if ! $found; then
    echo "(no descriptor file found)"
else
    # Display all found descriptor files
    for file in "${readme_files[@]}"; do
        if [ -e "$file" ]; then
            more "$file"
        fi
    done
fi

#-- revert to default colour
echo -e ${NC}

#-- now display directory listing
ls --color=auto -alhF
